<?php
// --- Demo: prepared-statement remediation for low.php (PoC) ---
$user = $_GET['username'] ?? '';
$pass = $_GET['password'] ?? '';
$pass = md5($pass);

// Autogenerated demo fix: use prepared statement to avoid SQL injection.
// REVIEW: ensure $mysqli/$conn variable is correct for this file.
$dbConn = isset($mysqli) ? $mysqli : (isset($conn) ? $conn : (isset($link) ? $link : null));
if ($dbConn) {
    $sql_tpl = "SELECT * FROM `users` WHERE user = ? AND password = ?";
    $stmt = @mysqli_prepare($dbConn, $sql_tpl);
    if ($stmt) {
        mysqli_stmt_bind_param($stmt, "ss", $user, $pass);
        mysqli_stmt_execute($stmt);
        $res = mysqli_stmt_get_result($stmt);
        // Fetch rows as needed
    } else {
        // Fallback to original query if prepare failed
        $query  = "SELECT * FROM `users` WHERE user = '$user' AND password = '$pass';";
        $result = mysqli_query($GLOBALS["___mysqli_ston"],  $query ) or die( '<pre>' . mysqli_error($GLOBALS["___mysqli_ston"]) . '</pre>' );
    }
} else {
    // No DB connection variable found — keep original behavior
    $query  = "SELECT * FROM `users` WHERE user = '$user' AND password = '$pass';";
    $result = mysqli_query($GLOBALS["___mysqli_ston"],  $query ) or die( '<pre>' . mysqli_error($GLOBALS["___mysqli_ston"]) . '</pre>' );
}
