// Autogenerated demo fix: use prepared statement to avoid SQL injection.
// REVIEW: ensure $mysqli/$conn variable is correct for this file.
$dbConn = isset($mysqli) ? $mysqli : (isset($conn) ? $conn : (isset($link) ? $link : null));
if ($dbConn) {
    $sql_tpl = "SELECT * FROM `users` WHERE user = ? AND password = ?";
    $stmt = @mysqli_prepare($dbConn, $sql_tpl);
    if ($stmt) {
        // bind parameters (two strings). Adjust types if necessary (e.g., "is")
        mysqli_stmt_bind_param($stmt, "ss", $user, $pass);
        mysqli_stmt_execute($stmt);
        $res = mysqli_stmt_get_result($stmt);
        // Fetch rows as needed, e.g.:
        // $row = mysqli_fetch_assoc($res);
    } else {
        // Fallback to original query if prepare failed (keeps behavior unchanged)
        $query  = "SELECT * FROM `users` WHERE user = '$user' AND password = '$pass';";
    }
} else {
    // No DB connection variable found — keep original behavior
    $query  = "SELECT * FROM `users` WHERE user = '$user' AND password = '$pass';";
}
